services:
  synod:
    container_name: synod
    image: synod:local
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-debug
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
    ports:
      - "4000:4000"
      - "4200:4200"
    depends_on:
      synod-db:
        condition: service_healthy
  synod-db:
    container_name: synod-db
    image: postgres:latest
    environment:
      POSTGRES_USER: synod
      POSTGRES_PASSWORD: synodpass
      POSTGRES_DB: synoddb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "4100:5432"